name: Deploy site

on:
  workflow_run:
    workflows: ["Build site"]
    branches: [main]
    types: [completed]

# Environment variables available to all jobs and steps in this workflow
env:
  APP_LOCATION: "/" # location of your client code
  API_LOCATION: "api" # location of your api source code - optional
  APP_ARTIFACT_LOCATION: "build" # location of client code build output
  AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }} # secret containing deployment token for your static web app

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build-site.yml
        workflow_conclusion: success
    
    - name: Azure login
      uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Set active account
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
            az account set -s ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Upload to Azure blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
            az storage blob upload-batch --account-name skillsmatrixproject -d '$web' -s ./production-files
    
    - name: Azure logout
      run: |
            az logout
